baseURL = 'https://solov.top/'
languageCode = 'en-us'
title = 'Day in the Life of a Senior Site Reliability Engineer (SRE)'
theme = "hugo-theme-learn"
#theme = "gohugo-theme-ananke"
enableRobotsTXT = true
uglyurls =  true
disableHugoGeneratorInject = false
googleAnalytics = "UA-105947713-1"

# Control TOC depth
[markup]
[markup.tableOfContents]
startLevel = 2
endLevel = 6
ordered = false
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = false

[outputs]
  home = [ "HTML", "RSS", "JSON", "WebAppManifest" ]
  section = [ "HTML", "RSS" ]

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]
[outputFormats.WebAppManifest]
  mediaType = "application/manifest+json"
  rel = "manifest"

[imaging]
  resampleFilter = "lanczos"
  quality = 90
  anchor = "smart"  # Anchor for cropping. Options include Smart and Center.

# Taxonomies.
[taxonomies]
  tag = "tags"
  category = "categories"
  publication_type = "publication_types"
  author = "authors"

# Related content.
[related]
  threshold = 80.0
  includeNewer = true
  toLower = true

  [[related.indices]]
    name = "title"
    weight = 60.0

  [[related.indices]]
    name = "summary"
    weight = 50.0

  [[related.indices]]
    name = "tags"
    weight = 80.0

  [[related.indices]]
    name = "categories"
    weight = 70.0

  [[related.indices]]
    name = "authors"
    weight = 20.0


[sitemap]
  changefreq = 'hourly'
  filename = 'sitemap.xml'
  priority = 0.5


[params.features]
[params.features.comment]
enable = true
[params.features.portfolio]
enable = true
[params.features.blog]
enable = true
[params.features.notes]
enable = true

[permalinks]
  '/' = '/:filename.html'
  posts = '/:year/:month/:title.html'
  authors = "/author/:slug/"
  tags = "/tag/:slug/"
  categories = "/category/:slug/"

# Install Wowchemy
#[module]
#  [[module.imports]]
#    path = "github.com/wowchemy/wowchemy-hugo-modules/wowchemy"
